/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import * as models from "../index.js";
import { AuditLockerError } from "./audit-locker-error.js";

/**
 * RFC 9457 Problem Details error response. All error responses follow this format. Match on `code` for programmatic handling; per-status narrowed schemas allOf this base.
 */
export type UnauthenticatedErrorData = {
  /**
   * URI reference identifying the error type
   */
  type: string;
  /**
   * Human-readable summary of the error type
   */
  title: string;
  status: models.UnauthenticatedErrorStatus;
  /**
   * Human-readable explanation specific to this occurrence
   */
  detail?: string | undefined;
  /**
   * URI reference identifying this specific occurrence (request ID)
   */
  instance?: string | undefined;
  code?: models.UnauthenticatedErrorCode | undefined;
};

/**
 * RFC 9457 Problem Details error response. All error responses follow this format. Match on `code` for programmatic handling; per-status narrowed schemas allOf this base.
 */
export class UnauthenticatedError extends AuditLockerError {
  /**
   * URI reference identifying the error type
   */
  type: string;
  /**
   * Human-readable summary of the error type
   */
  title: string;
  status: models.UnauthenticatedErrorStatus;
  /**
   * Human-readable explanation specific to this occurrence
   */
  detail?: string | undefined;
  /**
   * URI reference identifying this specific occurrence (request ID)
   */
  instance?: string | undefined;
  code?: models.UnauthenticatedErrorCode | undefined;

  /** The original data that was passed to this error instance. */
  data$: UnauthenticatedErrorData;

  constructor(
    err: UnauthenticatedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.title = err.title;
    this.status = err.status;
    if (err.detail != null) this.detail = err.detail;
    if (err.instance != null) this.instance = err.instance;
    if (err.code != null) this.code = err.code;

    this.name = "UnauthenticatedError";
  }
}

/** @internal */
export const UnauthenticatedError$inboundSchema: z.ZodMiniType<
  UnauthenticatedError,
  unknown
> = z.pipe(
  z.object({
    type: types.string(),
    title: types.string(),
    status: models.UnauthenticatedErrorStatus$inboundSchema,
    detail: types.optional(types.string()),
    instance: types.optional(types.string()),
    code: types.optional(models.UnauthenticatedErrorCode$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new UnauthenticatedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
