/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { AuditLockerCore } from "../core.js";
import { encodeJSON, encodeSimple } from "../lib/encodings.js";
import { matchStatusCode } from "../lib/http.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import { AuditLockerError } from "../models/errors/audit-locker-error.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/http-client-errors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/response-validation-error.js";
import { SDKValidationError } from "../models/errors/sdk-validation-error.js";
import * as operations from "../models/operations/index.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Ingest a single audit event
 *
 * @remarks
 * Accepts a single audit event, validates, and writes synchronously. Returns 201 Created with the event ID and server-assigned timestamp.
 */
export function eventsIngest(
  client: AuditLockerCore,
  request: operations.IngestEventRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    operations.IngestEventResponse,
    | errors.ValidationError
    | errors.UnauthenticatedError
    | errors.ScopeMismatchError
    | errors.IdempotencyConflictError
    | errors.PayloadTooLargeError
    | errors.UnsupportedMediaTypeError
    | errors.RateLimitedError
    | errors.InternalError
    | errors.ServiceUnavailableError
    | AuditLockerError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return new APIPromise($do(
    client,
    request,
    options,
  ));
}

async function $do(
  client: AuditLockerCore,
  request: operations.IngestEventRequest,
  options?: RequestOptions,
): Promise<
  [
    Result<
      operations.IngestEventResponse,
      | errors.ValidationError
      | errors.UnauthenticatedError
      | errors.ScopeMismatchError
      | errors.IdempotencyConflictError
      | errors.PayloadTooLargeError
      | errors.UnsupportedMediaTypeError
      | errors.RateLimitedError
      | errors.InternalError
      | errors.ServiceUnavailableError
      | AuditLockerError
      | ResponseValidationError
      | ConnectionError
      | RequestAbortedError
      | RequestTimeoutError
      | InvalidRequestError
      | UnexpectedClientError
      | SDKValidationError
    >,
    APICall,
  ]
> {
  const parsed = safeParse(
    request,
    (value) => z.parse(operations.IngestEventRequest$outboundSchema, value),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return [parsed, { status: "invalid" }];
  }
  const payload = parsed.value;
  const body = encodeJSON("body", payload.body, { explode: true });

  const path = pathToFunc("/v1/events")();

  const headers = new Headers(compactMap({
    "Content-Type": "application/json",
    Accept: "application/json",
    "idempotency-key": encodeSimple(
      "idempotency-key",
      payload["idempotency-key"],
      { explode: false, charEncoding: "none" },
    ),
  }));

  const secConfig = await extractSecurity(client._options.apiKey);
  const securityInput = secConfig == null ? {} : { apiKey: secConfig };
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    options: client._options,
    baseURL: options?.serverURL ?? client._baseURL ?? "",
    operationID: "ingestEvent",
    oAuth2Scopes: null,

    resolvedSecurity: requestSecurity,

    securitySource: client._options.apiKey,
    retryConfig: options?.retries
      || client._options.retryConfig
      || {
        strategy: "backoff",
        backoff: {
          initialInterval: 500,
          maxInterval: 30000,
          exponent: 1.5,
          maxElapsedTime: 60000,
        },
        retryConnectionErrors: true,
      }
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["5XX", "408", "429"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "POST",
    baseURL: options?.serverURL,
    path: path,
    headers: headers,
    body: body,
    userAgent: client._options.userAgent,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    isErrorStatusCode: (statusCode: number) =>
      matchStatusCode({ status: statusCode } as Response, ["4XX", "5XX"]),
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const responseFields = {
    HttpMeta: { Response: response, Request: req },
  };

  const [result] = await M.match<
    operations.IngestEventResponse,
    | errors.ValidationError
    | errors.UnauthenticatedError
    | errors.ScopeMismatchError
    | errors.IdempotencyConflictError
    | errors.PayloadTooLargeError
    | errors.UnsupportedMediaTypeError
    | errors.RateLimitedError
    | errors.InternalError
    | errors.ServiceUnavailableError
    | AuditLockerError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >(
    M.json(201, operations.IngestEventResponse$inboundSchema, {
      hdrs: true,
      key: "Result",
    }),
    M.jsonErr(400, errors.ValidationError$inboundSchema, {
      ctype: "application/problem+json",
    }),
    M.jsonErr(401, errors.UnauthenticatedError$inboundSchema, {
      ctype: "application/problem+json",
    }),
    M.jsonErr(403, errors.ScopeMismatchError$inboundSchema, {
      ctype: "application/problem+json",
    }),
    M.jsonErr(409, errors.IdempotencyConflictError$inboundSchema, {
      ctype: "application/problem+json",
    }),
    M.jsonErr(413, errors.PayloadTooLargeError$inboundSchema, {
      ctype: "application/problem+json",
    }),
    M.jsonErr(415, errors.UnsupportedMediaTypeError$inboundSchema, {
      ctype: "application/problem+json",
    }),
    M.jsonErr(429, errors.RateLimitedError$inboundSchema, {
      ctype: "application/problem+json",
    }),
    M.jsonErr(500, errors.InternalError$inboundSchema, {
      ctype: "application/problem+json",
    }),
    M.jsonErr(503, errors.ServiceUnavailableError$inboundSchema, {
      ctype: "application/problem+json",
    }),
    M.fail("4XX"),
    M.fail("5XX"),
  )(response, req, { extraFields: responseFields });
  if (!result.ok) {
    return [result, { status: "complete", request: req, response }];
  }

  return [result, { status: "complete", request: req, response }];
}
