/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventsGet } from "../funcs/events-get.js";
import { eventsIngestBatch } from "../funcs/events-ingest-batch.js";
import { eventsIngest } from "../funcs/events-ingest.js";
import { eventsList } from "../funcs/events-list.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Events extends ClientSDK {
  /**
   * Ingest a single audit event
   *
   * @remarks
   * Accepts a single audit event, validates, and writes synchronously. Returns 201 Created with the event ID and server-assigned timestamp.
   */
  async ingest(
    request: operations.IngestEventRequest,
    options?: RequestOptions,
  ): Promise<operations.IngestEventResponse> {
    return unwrapAsync(eventsIngest(
      this,
      request,
      options,
    ));
  }

  /**
   * Query audit events
   *
   * @remarks
   * Returns a paginated list of audit events matching the specified filters. Use the `cursor` parameter to fetch subsequent pages.
   */
  async list(
    request?: operations.ListEventsRequest | undefined,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.ListEventsResponse, { cursor: string }>> {
    return unwrapResultIterator(eventsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Ingest a batch of audit events
   *
   * @remarks
   * Accepts up to 500 audit events, validates each, and writes valid events synchronously. Returns 207 Multi-Status with per-event results. Some events may succeed while others fail validation.
   */
  async ingestBatch(
    request: operations.IngestEventBatchRequest,
    options?: RequestOptions,
  ): Promise<operations.IngestEventBatchResponse> {
    return unwrapAsync(eventsIngestBatch(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a single audit event
   *
   * @remarks
   * Retrieves a single audit event by its ID. Returns 404 if the event does not exist or belongs to a different project.
   */
  async get(
    request: operations.GetEventRequest,
    options?: RequestOptions,
  ): Promise<operations.GetEventResponse> {
    return unwrapAsync(eventsGet(
      this,
      request,
      options,
    ));
  }
}
