/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Events } from "./events.js";

export class AuditLocker extends ClientSDK {
  private _events?: Events;
  get events(): Events {
    return (this._events ??= new Events(this._options));
  }
}
