/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetEventRequest = {
  /**
   * Event identifier.
   */
  id: string;
};

export type GetEventResponse = {
  headers: { [k: string]: Array<string> };
  result: models.AuditEventOutput;
};

/** @internal */
export type GetEventRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetEventRequest$outboundSchema: z.ZodMiniType<
  GetEventRequest$Outbound,
  GetEventRequest
> = z.object({
  id: z.string(),
});

export function getEventRequestToJSON(
  getEventRequest: GetEventRequest,
): string {
  return JSON.stringify(GetEventRequest$outboundSchema.parse(getEventRequest));
}

/** @internal */
export const GetEventResponse$inboundSchema: z.ZodMiniType<
  GetEventResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.AuditEventOutput$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getEventResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetEventResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetEventResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetEventResponse' from JSON`,
  );
}
