/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type IngestEventBatchRequest = {
  /**
   * Client-generated unique key for idempotent requests. Duplicate requests with the same key and payload within 24 hours return the cached response. Same key with different payload returns 409 Conflict.
   */
  idempotencyKey?: string | undefined;
  body: models.BatchIngestRequest;
};

export type IngestEventBatchResponse = {
  headers: { [k: string]: Array<string> };
  result: models.BatchIngestResponse;
};

/** @internal */
export type IngestEventBatchRequest$Outbound = {
  "idempotency-key"?: string | undefined;
  body: models.BatchIngestRequest$Outbound;
};

/** @internal */
export const IngestEventBatchRequest$outboundSchema: z.ZodMiniType<
  IngestEventBatchRequest$Outbound,
  IngestEventBatchRequest
> = z.pipe(
  z.object({
    idempotencyKey: z.optional(z.string()),
    body: models.BatchIngestRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "idempotency-key",
    });
  }),
);

export function ingestEventBatchRequestToJSON(
  ingestEventBatchRequest: IngestEventBatchRequest,
): string {
  return JSON.stringify(
    IngestEventBatchRequest$outboundSchema.parse(ingestEventBatchRequest),
  );
}

/** @internal */
export const IngestEventBatchResponse$inboundSchema: z.ZodMiniType<
  IngestEventBatchResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.BatchIngestResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function ingestEventBatchResponseFromJSON(
  jsonString: string,
): SafeParseResult<IngestEventBatchResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IngestEventBatchResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IngestEventBatchResponse' from JSON`,
  );
}
