/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type IngestEventRequest = {
  /**
   * Client-generated unique key for idempotent requests. Duplicate requests with the same key and payload within 24 hours return the cached response. Same key with different payload returns 409 Conflict.
   */
  idempotencyKey?: string | undefined;
  body: models.AuditEventInput;
};

export type IngestEventResponse = {
  headers: { [k: string]: Array<string> };
  result: models.IngestResponse;
};

/** @internal */
export type IngestEventRequest$Outbound = {
  "idempotency-key"?: string | undefined;
  body: models.AuditEventInput$Outbound;
};

/** @internal */
export const IngestEventRequest$outboundSchema: z.ZodMiniType<
  IngestEventRequest$Outbound,
  IngestEventRequest
> = z.pipe(
  z.object({
    idempotencyKey: z.optional(z.string()),
    body: models.AuditEventInput$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "idempotency-key",
    });
  }),
);

export function ingestEventRequestToJSON(
  ingestEventRequest: IngestEventRequest,
): string {
  return JSON.stringify(
    IngestEventRequest$outboundSchema.parse(ingestEventRequest),
  );
}

/** @internal */
export const IngestEventResponse$inboundSchema: z.ZodMiniType<
  IngestEventResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.IngestResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function ingestEventResponseFromJSON(
  jsonString: string,
): SafeParseResult<IngestEventResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IngestEventResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IngestEventResponse' from JSON`,
  );
}
