/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListEventsRequest = {
  organizationId?: string | undefined;
  actorId?: string | undefined;
  action?: string | undefined;
  targetType?: string | undefined;
  targetId?: string | undefined;
  receivedAtGte?: Date | undefined;
  receivedAtLt?: Date | undefined;
  limit?: number | undefined;
  cursor?: string | undefined;
  enrichActors?: boolean | undefined;
};

export type ListEventsResponse = {
  headers: { [k: string]: Array<string> };
  result: models.QueryResponse;
};

/** @internal */
export type ListEventsRequest$Outbound = {
  organization_id?: string | undefined;
  actor_id?: string | undefined;
  action?: string | undefined;
  target_type?: string | undefined;
  target_id?: string | undefined;
  received_at_gte?: string | undefined;
  received_at_lt?: string | undefined;
  limit: number;
  cursor?: string | undefined;
  enrich_actors: boolean;
};

/** @internal */
export const ListEventsRequest$outboundSchema: z.ZodMiniType<
  ListEventsRequest$Outbound,
  ListEventsRequest
> = z.pipe(
  z.object({
    organizationId: z.optional(z.string()),
    actorId: z.optional(z.string()),
    action: z.optional(z.string()),
    targetType: z.optional(z.string()),
    targetId: z.optional(z.string()),
    receivedAtGte: z.optional(
      z.pipe(z.date(), z.transform(v => v.toISOString())),
    ),
    receivedAtLt: z.optional(
      z.pipe(z.date(), z.transform(v => v.toISOString())),
    ),
    limit: z._default(z.int(), 50),
    cursor: z.optional(z.string()),
    enrichActors: z._default(z.boolean(), true),
  }),
  z.transform((v) => {
    return remap$(v, {
      organizationId: "organization_id",
      actorId: "actor_id",
      targetType: "target_type",
      targetId: "target_id",
      receivedAtGte: "received_at_gte",
      receivedAtLt: "received_at_lt",
      enrichActors: "enrich_actors",
    });
  }),
);

export function listEventsRequestToJSON(
  listEventsRequest: ListEventsRequest,
): string {
  return JSON.stringify(
    ListEventsRequest$outboundSchema.parse(listEventsRequest),
  );
}

/** @internal */
export const ListEventsResponse$inboundSchema: z.ZodMiniType<
  ListEventsResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: models.QueryResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function listEventsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListEventsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListEventsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListEventsResponse' from JSON`,
  );
}
