/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smart-union.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const AuditEventOutputTimestampAnomalyFutureSkewExceeded = {
  FutureSkewExceeded: "future_skew_exceeded",
} as const;
export type AuditEventOutputTimestampAnomalyFutureSkewExceeded = ClosedEnum<
  typeof AuditEventOutputTimestampAnomalyFutureSkewExceeded
>;

export const AuditEventOutputTimestampAnomalyPastWindowExceeded = {
  PastWindowExceeded: "past_window_exceeded",
} as const;
export type AuditEventOutputTimestampAnomalyPastWindowExceeded = ClosedEnum<
  typeof AuditEventOutputTimestampAnomalyPastWindowExceeded
>;

export type AuditEventOutputTimestampAnomalyUnion =
  | AuditEventOutputTimestampAnomalyPastWindowExceeded
  | AuditEventOutputTimestampAnomalyFutureSkewExceeded;

export type AuditEventOutputActor = {
  id: string;
  type: string;
  name: string | null;
};

export type AuditEventOutputTarget = {
  type: string;
  id: string;
  name: string | null;
};

/**
 * A single audit event with full forensic context.
 */
export type AuditEventOutput = {
  /**
   * Unique identifier for the event.
   */
  id: string;
  /**
   * Identifier of the environment this event belongs to.
   */
  environmentId: string;
  organizationId: string;
  receivedAt: Date;
  timestamp: Date;
  timestampAnomaly:
    | AuditEventOutputTimestampAnomalyPastWindowExceeded
    | AuditEventOutputTimestampAnomalyFutureSkewExceeded
    | null;
  actor: AuditEventOutputActor;
  action: string;
  targets: Array<AuditEventOutputTarget>;
  source: string | null;
  metadata: { [k: string]: any } | null;
};

/** @internal */
export const AuditEventOutputTimestampAnomalyFutureSkewExceeded$inboundSchema:
  z.ZodMiniEnum<typeof AuditEventOutputTimestampAnomalyFutureSkewExceeded> = z
    .enum(AuditEventOutputTimestampAnomalyFutureSkewExceeded);

/** @internal */
export const AuditEventOutputTimestampAnomalyPastWindowExceeded$inboundSchema:
  z.ZodMiniEnum<typeof AuditEventOutputTimestampAnomalyPastWindowExceeded> = z
    .enum(AuditEventOutputTimestampAnomalyPastWindowExceeded);

/** @internal */
export const AuditEventOutputTimestampAnomalyUnion$inboundSchema: z.ZodMiniType<
  AuditEventOutputTimestampAnomalyUnion,
  unknown
> = smartUnion([
  AuditEventOutputTimestampAnomalyPastWindowExceeded$inboundSchema,
  AuditEventOutputTimestampAnomalyFutureSkewExceeded$inboundSchema,
]);

export function auditEventOutputTimestampAnomalyUnionFromJSON(
  jsonString: string,
): SafeParseResult<AuditEventOutputTimestampAnomalyUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AuditEventOutputTimestampAnomalyUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuditEventOutputTimestampAnomalyUnion' from JSON`,
  );
}

/** @internal */
export const AuditEventOutputActor$inboundSchema: z.ZodMiniType<
  AuditEventOutputActor,
  unknown
> = z.object({
  id: types.string(),
  type: types.string(),
  name: types.nullable(types.string()),
});

export function auditEventOutputActorFromJSON(
  jsonString: string,
): SafeParseResult<AuditEventOutputActor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuditEventOutputActor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuditEventOutputActor' from JSON`,
  );
}

/** @internal */
export const AuditEventOutputTarget$inboundSchema: z.ZodMiniType<
  AuditEventOutputTarget,
  unknown
> = z.object({
  type: types.string(),
  id: types.string(),
  name: types.nullable(types.string()),
});

export function auditEventOutputTargetFromJSON(
  jsonString: string,
): SafeParseResult<AuditEventOutputTarget, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuditEventOutputTarget$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuditEventOutputTarget' from JSON`,
  );
}

/** @internal */
export const AuditEventOutput$inboundSchema: z.ZodMiniType<
  AuditEventOutput,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    environment_id: types.string(),
    organization_id: types.string(),
    received_at: types.date(),
    timestamp: types.date(),
    timestamp_anomaly: types.nullable(
      smartUnion([
        AuditEventOutputTimestampAnomalyPastWindowExceeded$inboundSchema,
        AuditEventOutputTimestampAnomalyFutureSkewExceeded$inboundSchema,
      ]),
    ),
    actor: z.lazy(() => AuditEventOutputActor$inboundSchema),
    action: types.string(),
    targets: z.array(z.lazy(() => AuditEventOutputTarget$inboundSchema)),
    source: types.nullable(types.string()),
    metadata: types.nullable(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "environment_id": "environmentId",
      "organization_id": "organizationId",
      "received_at": "receivedAt",
      "timestamp_anomaly": "timestampAnomaly",
    });
  }),
);

export function auditEventOutputFromJSON(
  jsonString: string,
): SafeParseResult<AuditEventOutput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuditEventOutput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuditEventOutput' from JSON`,
  );
}
