/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type AuditEventInputActor = {
  id: string;
  type: string;
  name?: string | undefined;
};

export type AuditEventInputTarget = {
  type: string;
  id: string;
  name?: string | undefined;
};

export type AuditEventInput = {
  organizationId: string;
  actor: AuditEventInputActor;
  action: string;
  targets: Array<AuditEventInputTarget>;
  source?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
  timestamp?: Date | undefined;
};

/** @internal */
export type AuditEventInputActor$Outbound = {
  id: string;
  type: string;
  name?: string | undefined;
};

/** @internal */
export const AuditEventInputActor$outboundSchema: z.ZodMiniType<
  AuditEventInputActor$Outbound,
  AuditEventInputActor
> = z.object({
  id: z.string(),
  type: z.string(),
  name: z.optional(z.string()),
});

export function auditEventInputActorToJSON(
  auditEventInputActor: AuditEventInputActor,
): string {
  return JSON.stringify(
    AuditEventInputActor$outboundSchema.parse(auditEventInputActor),
  );
}

/** @internal */
export type AuditEventInputTarget$Outbound = {
  type: string;
  id: string;
  name?: string | undefined;
};

/** @internal */
export const AuditEventInputTarget$outboundSchema: z.ZodMiniType<
  AuditEventInputTarget$Outbound,
  AuditEventInputTarget
> = z.object({
  type: z.string(),
  id: z.string(),
  name: z.optional(z.string()),
});

export function auditEventInputTargetToJSON(
  auditEventInputTarget: AuditEventInputTarget,
): string {
  return JSON.stringify(
    AuditEventInputTarget$outboundSchema.parse(auditEventInputTarget),
  );
}

/** @internal */
export type AuditEventInput$Outbound = {
  organization_id: string;
  actor: AuditEventInputActor$Outbound;
  action: string;
  targets: Array<AuditEventInputTarget$Outbound>;
  source?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
  timestamp?: string | undefined;
};

/** @internal */
export const AuditEventInput$outboundSchema: z.ZodMiniType<
  AuditEventInput$Outbound,
  AuditEventInput
> = z.pipe(
  z.object({
    organizationId: z.string(),
    actor: z.lazy(() => AuditEventInputActor$outboundSchema),
    action: z.string(),
    targets: z.array(z.lazy(() => AuditEventInputTarget$outboundSchema)),
    source: z.optional(z.string()),
    metadata: z.optional(z.record(z.string(), z.any())),
    timestamp: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
  }),
  z.transform((v) => {
    return remap$(v, {
      organizationId: "organization_id",
    });
  }),
);

export function auditEventInputToJSON(
  auditEventInput: AuditEventInput,
): string {
  return JSON.stringify(AuditEventInput$outboundSchema.parse(auditEventInput));
}
