/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminated-union.js";
import { discriminatedUnion } from "../types/discriminated-union.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  BatchEventResultError,
  BatchEventResultError$inboundSchema,
} from "./batch-event-result-error.js";
import {
  BatchEventResultSuccess,
  BatchEventResultSuccess$inboundSchema,
} from "./batch-event-result-success.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Result =
  | BatchEventResultSuccess
  | BatchEventResultError
  | discriminatedUnionTypes.Unknown<"status">;

/**
 * Multi-status result for batch ingest — inspect `results[].status` to distinguish accepted from rejected events.
 */
export type BatchIngestResponse = {
  /**
   * Number of events successfully ingested
   */
  accepted: number;
  /**
   * Number of events that failed validation
   */
  rejected: number;
  /**
   * Per-event results in the same order as the input array
   */
  results: Array<
    | BatchEventResultSuccess
    | BatchEventResultError
    | discriminatedUnionTypes.Unknown<"status">
  >;
};

/** @internal */
export const Result$inboundSchema: z.ZodMiniType<Result, unknown> =
  discriminatedUnion("status", {
    accepted: BatchEventResultSuccess$inboundSchema,
    rejected: BatchEventResultError$inboundSchema,
  });

export function resultFromJSON(
  jsonString: string,
): SafeParseResult<Result, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Result$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Result' from JSON`,
  );
}

/** @internal */
export const BatchIngestResponse$inboundSchema: z.ZodMiniType<
  BatchIngestResponse,
  unknown
> = z.object({
  accepted: types.number(),
  rejected: types.number(),
  results: z.array(
    discriminatedUnion("status", {
      accepted: BatchEventResultSuccess$inboundSchema,
      rejected: BatchEventResultError$inboundSchema,
    }),
  ),
});

export function batchIngestResponseFromJSON(
  jsonString: string,
): SafeParseResult<BatchIngestResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BatchIngestResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BatchIngestResponse' from JSON`,
  );
}
