/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type BatchIngestRequestActor = {
  id: string;
  type: string;
  name?: string | undefined;
};

export type BatchIngestRequestTarget = {
  type: string;
  id: string;
  name?: string | undefined;
};

export type BatchIngestRequestEvent = {
  organizationId: string;
  actor: BatchIngestRequestActor;
  action: string;
  targets: Array<BatchIngestRequestTarget>;
  source?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
  timestamp?: Date | undefined;
};

export type BatchIngestRequest = {
  events: Array<BatchIngestRequestEvent>;
};

/** @internal */
export type BatchIngestRequestActor$Outbound = {
  id: string;
  type: string;
  name?: string | undefined;
};

/** @internal */
export const BatchIngestRequestActor$outboundSchema: z.ZodMiniType<
  BatchIngestRequestActor$Outbound,
  BatchIngestRequestActor
> = z.object({
  id: z.string(),
  type: z.string(),
  name: z.optional(z.string()),
});

export function batchIngestRequestActorToJSON(
  batchIngestRequestActor: BatchIngestRequestActor,
): string {
  return JSON.stringify(
    BatchIngestRequestActor$outboundSchema.parse(batchIngestRequestActor),
  );
}

/** @internal */
export type BatchIngestRequestTarget$Outbound = {
  type: string;
  id: string;
  name?: string | undefined;
};

/** @internal */
export const BatchIngestRequestTarget$outboundSchema: z.ZodMiniType<
  BatchIngestRequestTarget$Outbound,
  BatchIngestRequestTarget
> = z.object({
  type: z.string(),
  id: z.string(),
  name: z.optional(z.string()),
});

export function batchIngestRequestTargetToJSON(
  batchIngestRequestTarget: BatchIngestRequestTarget,
): string {
  return JSON.stringify(
    BatchIngestRequestTarget$outboundSchema.parse(batchIngestRequestTarget),
  );
}

/** @internal */
export type BatchIngestRequestEvent$Outbound = {
  organization_id: string;
  actor: BatchIngestRequestActor$Outbound;
  action: string;
  targets: Array<BatchIngestRequestTarget$Outbound>;
  source?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
  timestamp?: string | undefined;
};

/** @internal */
export const BatchIngestRequestEvent$outboundSchema: z.ZodMiniType<
  BatchIngestRequestEvent$Outbound,
  BatchIngestRequestEvent
> = z.pipe(
  z.object({
    organizationId: z.string(),
    actor: z.lazy(() => BatchIngestRequestActor$outboundSchema),
    action: z.string(),
    targets: z.array(z.lazy(() => BatchIngestRequestTarget$outboundSchema)),
    source: z.optional(z.string()),
    metadata: z.optional(z.record(z.string(), z.any())),
    timestamp: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
  }),
  z.transform((v) => {
    return remap$(v, {
      organizationId: "organization_id",
    });
  }),
);

export function batchIngestRequestEventToJSON(
  batchIngestRequestEvent: BatchIngestRequestEvent,
): string {
  return JSON.stringify(
    BatchIngestRequestEvent$outboundSchema.parse(batchIngestRequestEvent),
  );
}

/** @internal */
export type BatchIngestRequest$Outbound = {
  events: Array<BatchIngestRequestEvent$Outbound>;
};

/** @internal */
export const BatchIngestRequest$outboundSchema: z.ZodMiniType<
  BatchIngestRequest$Outbound,
  BatchIngestRequest
> = z.object({
  events: z.array(z.lazy(() => BatchIngestRequestEvent$outboundSchema)),
});

export function batchIngestRequestToJSON(
  batchIngestRequest: BatchIngestRequest,
): string {
  return JSON.stringify(
    BatchIngestRequest$outboundSchema.parse(batchIngestRequest),
  );
}
