/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const IdempotencyConflictErrorStatus = {
  FourHundredAndNine: 409,
} as const;
export type IdempotencyConflictErrorStatus = ClosedEnum<
  typeof IdempotencyConflictErrorStatus
>;

export const IdempotencyConflictErrorCode = {
  IdempotencyConflict: "idempotency_conflict",
} as const;
export type IdempotencyConflictErrorCode = ClosedEnum<
  typeof IdempotencyConflictErrorCode
>;

/** @internal */
export const IdempotencyConflictErrorStatus$inboundSchema: z.ZodMiniEnum<
  typeof IdempotencyConflictErrorStatus
> = z.enum(IdempotencyConflictErrorStatus);

/** @internal */
export const IdempotencyConflictErrorCode$inboundSchema: z.ZodMiniEnum<
  typeof IdempotencyConflictErrorCode
> = z.enum(IdempotencyConflictErrorCode);
