/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smart-union.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const IngestResponseTimestampAnomalyFutureSkewExceeded = {
  FutureSkewExceeded: "future_skew_exceeded",
} as const;
export type IngestResponseTimestampAnomalyFutureSkewExceeded = ClosedEnum<
  typeof IngestResponseTimestampAnomalyFutureSkewExceeded
>;

export const IngestResponseTimestampAnomalyPastWindowExceeded = {
  PastWindowExceeded: "past_window_exceeded",
} as const;
export type IngestResponseTimestampAnomalyPastWindowExceeded = ClosedEnum<
  typeof IngestResponseTimestampAnomalyPastWindowExceeded
>;

/**
 * Non-null when the supplied timestamp fell outside the accepted window around received_at.
 */
export type IngestResponseTimestampAnomalyUnion =
  | IngestResponseTimestampAnomalyPastWindowExceeded
  | IngestResponseTimestampAnomalyFutureSkewExceeded;

/**
 * Event accepted and persisted.
 */
export type IngestResponse = {
  /**
   * Unique identifier for the created event.
   */
  id: string;
  /**
   * ISO 8601 timestamp when the server accepted the event.
   */
  receivedAt: Date;
  /**
   * Non-null when the supplied timestamp fell outside the accepted window around received_at.
   */
  timestampAnomaly:
    | IngestResponseTimestampAnomalyPastWindowExceeded
    | IngestResponseTimestampAnomalyFutureSkewExceeded
    | null;
  /**
   * Field paths that were redacted by data-loss-prevention scanning, if any.
   */
  dlpRedactedFields: Array<string> | null;
};

/** @internal */
export const IngestResponseTimestampAnomalyFutureSkewExceeded$inboundSchema:
  z.ZodMiniEnum<typeof IngestResponseTimestampAnomalyFutureSkewExceeded> = z
    .enum(IngestResponseTimestampAnomalyFutureSkewExceeded);

/** @internal */
export const IngestResponseTimestampAnomalyPastWindowExceeded$inboundSchema:
  z.ZodMiniEnum<typeof IngestResponseTimestampAnomalyPastWindowExceeded> = z
    .enum(IngestResponseTimestampAnomalyPastWindowExceeded);

/** @internal */
export const IngestResponseTimestampAnomalyUnion$inboundSchema: z.ZodMiniType<
  IngestResponseTimestampAnomalyUnion,
  unknown
> = smartUnion([
  IngestResponseTimestampAnomalyPastWindowExceeded$inboundSchema,
  IngestResponseTimestampAnomalyFutureSkewExceeded$inboundSchema,
]);

export function ingestResponseTimestampAnomalyUnionFromJSON(
  jsonString: string,
): SafeParseResult<IngestResponseTimestampAnomalyUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      IngestResponseTimestampAnomalyUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IngestResponseTimestampAnomalyUnion' from JSON`,
  );
}

/** @internal */
export const IngestResponse$inboundSchema: z.ZodMiniType<
  IngestResponse,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    received_at: types.date(),
    timestamp_anomaly: types.nullable(
      smartUnion([
        IngestResponseTimestampAnomalyPastWindowExceeded$inboundSchema,
        IngestResponseTimestampAnomalyFutureSkewExceeded$inboundSchema,
      ]),
    ),
    dlp_redacted_fields: types.nullable(z.array(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "received_at": "receivedAt",
      "timestamp_anomaly": "timestampAnomaly",
      "dlp_redacted_fields": "dlpRedactedFields",
    });
  }),
);

export function ingestResponseFromJSON(
  jsonString: string,
): SafeParseResult<IngestResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IngestResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IngestResponse' from JSON`,
  );
}
