/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const InternalErrorStatus = {
  FiveHundred: 500,
} as const;
export type InternalErrorStatus = ClosedEnum<typeof InternalErrorStatus>;

export const InternalErrorCode = {
  InternalError: "internal_error",
} as const;
export type InternalErrorCode = ClosedEnum<typeof InternalErrorCode>;

/** @internal */
export const InternalErrorStatus$inboundSchema: z.ZodMiniEnum<
  typeof InternalErrorStatus
> = z.enum(InternalErrorStatus);

/** @internal */
export const InternalErrorCode$inboundSchema: z.ZodMiniEnum<
  typeof InternalErrorCode
> = z.enum(InternalErrorCode);
