/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { ClosedEnum, OpenEnum } from "../types/enums.js";

export const NotFoundErrorStatus = {
  FourHundredAndFour: 404,
} as const;
export type NotFoundErrorStatus = ClosedEnum<typeof NotFoundErrorStatus>;

export const NotFoundErrorCode = {
  NotFound: "not_found",
  EnvironmentNotFound: "environment_not_found",
} as const;
export type NotFoundErrorCode = OpenEnum<typeof NotFoundErrorCode>;

/** @internal */
export const NotFoundErrorStatus$inboundSchema: z.ZodMiniEnum<
  typeof NotFoundErrorStatus
> = z.enum(NotFoundErrorStatus);

/** @internal */
export const NotFoundErrorCode$inboundSchema: z.ZodMiniType<
  NotFoundErrorCode,
  unknown
> = openEnums.inboundSchema(NotFoundErrorCode);
