/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const PayloadTooLargeErrorStatus = {
  FourHundredAndThirteen: 413,
} as const;
export type PayloadTooLargeErrorStatus = ClosedEnum<
  typeof PayloadTooLargeErrorStatus
>;

export const PayloadTooLargeErrorCode = {
  PayloadTooLarge: "payload_too_large",
} as const;
export type PayloadTooLargeErrorCode = ClosedEnum<
  typeof PayloadTooLargeErrorCode
>;

/** @internal */
export const PayloadTooLargeErrorStatus$inboundSchema: z.ZodMiniEnum<
  typeof PayloadTooLargeErrorStatus
> = z.enum(PayloadTooLargeErrorStatus);

/** @internal */
export const PayloadTooLargeErrorCode$inboundSchema: z.ZodMiniEnum<
  typeof PayloadTooLargeErrorCode
> = z.enum(PayloadTooLargeErrorCode);
