/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * RFC 9457 Problem Details error response. All error responses follow this format. Match on `code` for programmatic handling; per-status narrowed schemas allOf this base.
 */
export type ProblemDetails = {
  /**
   * URI reference identifying the error type
   */
  type: string;
  /**
   * Human-readable summary of the error type
   */
  title: string;
  /**
   * HTTP status code
   */
  status: number;
  /**
   * Human-readable explanation specific to this occurrence
   */
  detail?: string | undefined;
  /**
   * URI reference identifying this specific occurrence (request ID)
   */
  instance?: string | undefined;
  /**
   * Machine-readable error code for programmatic handling. Per-status narrowed schemas (ValidationError, RateLimitedError, …) constrain this to an audience-filtered enum.
   */
  code?: string | undefined;
};

/** @internal */
export const ProblemDetails$inboundSchema: z.ZodMiniType<
  ProblemDetails,
  unknown
> = z.object({
  type: types.string(),
  title: types.string(),
  status: types.number(),
  detail: types.optional(types.string()),
  instance: types.optional(types.string()),
  code: types.optional(types.string()),
});

export function problemDetailsFromJSON(
  jsonString: string,
): SafeParseResult<ProblemDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProblemDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProblemDetails' from JSON`,
  );
}
