/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smart-union.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const QueryResponseTimestampAnomalyFutureSkewExceeded = {
  FutureSkewExceeded: "future_skew_exceeded",
} as const;
export type QueryResponseTimestampAnomalyFutureSkewExceeded = ClosedEnum<
  typeof QueryResponseTimestampAnomalyFutureSkewExceeded
>;

export const QueryResponseTimestampAnomalyPastWindowExceeded = {
  PastWindowExceeded: "past_window_exceeded",
} as const;
export type QueryResponseTimestampAnomalyPastWindowExceeded = ClosedEnum<
  typeof QueryResponseTimestampAnomalyPastWindowExceeded
>;

export type QueryResponseTimestampAnomalyUnion =
  | QueryResponseTimestampAnomalyPastWindowExceeded
  | QueryResponseTimestampAnomalyFutureSkewExceeded;

export type QueryResponseActor = {
  id: string;
  type: string;
  name: string | null;
};

export type QueryResponseTarget = {
  type: string;
  id: string;
  name: string | null;
};

/**
 * A single audit event with full forensic context.
 */
export type QueryResponseEvent = {
  /**
   * Unique identifier for the event.
   */
  id: string;
  /**
   * Identifier of the environment this event belongs to.
   */
  environmentId: string;
  organizationId: string;
  receivedAt: Date;
  timestamp: Date;
  timestampAnomaly:
    | QueryResponseTimestampAnomalyPastWindowExceeded
    | QueryResponseTimestampAnomalyFutureSkewExceeded
    | null;
  actor: QueryResponseActor;
  action: string;
  targets: Array<QueryResponseTarget>;
  source: string | null;
  metadata: { [k: string]: any } | null;
};

/**
 * Paginated list of audit events matching the supplied filters.
 */
export type QueryResponse = {
  events: Array<QueryResponseEvent>;
  nextCursor: string | null;
};

/** @internal */
export const QueryResponseTimestampAnomalyFutureSkewExceeded$inboundSchema:
  z.ZodMiniEnum<typeof QueryResponseTimestampAnomalyFutureSkewExceeded> = z
    .enum(QueryResponseTimestampAnomalyFutureSkewExceeded);

/** @internal */
export const QueryResponseTimestampAnomalyPastWindowExceeded$inboundSchema:
  z.ZodMiniEnum<typeof QueryResponseTimestampAnomalyPastWindowExceeded> = z
    .enum(QueryResponseTimestampAnomalyPastWindowExceeded);

/** @internal */
export const QueryResponseTimestampAnomalyUnion$inboundSchema: z.ZodMiniType<
  QueryResponseTimestampAnomalyUnion,
  unknown
> = smartUnion([
  QueryResponseTimestampAnomalyPastWindowExceeded$inboundSchema,
  QueryResponseTimestampAnomalyFutureSkewExceeded$inboundSchema,
]);

export function queryResponseTimestampAnomalyUnionFromJSON(
  jsonString: string,
): SafeParseResult<QueryResponseTimestampAnomalyUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      QueryResponseTimestampAnomalyUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryResponseTimestampAnomalyUnion' from JSON`,
  );
}

/** @internal */
export const QueryResponseActor$inboundSchema: z.ZodMiniType<
  QueryResponseActor,
  unknown
> = z.object({
  id: types.string(),
  type: types.string(),
  name: types.nullable(types.string()),
});

export function queryResponseActorFromJSON(
  jsonString: string,
): SafeParseResult<QueryResponseActor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryResponseActor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryResponseActor' from JSON`,
  );
}

/** @internal */
export const QueryResponseTarget$inboundSchema: z.ZodMiniType<
  QueryResponseTarget,
  unknown
> = z.object({
  type: types.string(),
  id: types.string(),
  name: types.nullable(types.string()),
});

export function queryResponseTargetFromJSON(
  jsonString: string,
): SafeParseResult<QueryResponseTarget, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryResponseTarget$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryResponseTarget' from JSON`,
  );
}

/** @internal */
export const QueryResponseEvent$inboundSchema: z.ZodMiniType<
  QueryResponseEvent,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    environment_id: types.string(),
    organization_id: types.string(),
    received_at: types.date(),
    timestamp: types.date(),
    timestamp_anomaly: types.nullable(
      smartUnion([
        QueryResponseTimestampAnomalyPastWindowExceeded$inboundSchema,
        QueryResponseTimestampAnomalyFutureSkewExceeded$inboundSchema,
      ]),
    ),
    actor: z.lazy(() => QueryResponseActor$inboundSchema),
    action: types.string(),
    targets: z.array(z.lazy(() => QueryResponseTarget$inboundSchema)),
    source: types.nullable(types.string()),
    metadata: types.nullable(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "environment_id": "environmentId",
      "organization_id": "organizationId",
      "received_at": "receivedAt",
      "timestamp_anomaly": "timestampAnomaly",
    });
  }),
);

export function queryResponseEventFromJSON(
  jsonString: string,
): SafeParseResult<QueryResponseEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryResponseEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryResponseEvent' from JSON`,
  );
}

/** @internal */
export const QueryResponse$inboundSchema: z.ZodMiniType<
  QueryResponse,
  unknown
> = z.pipe(
  z.object({
    events: z.array(z.lazy(() => QueryResponseEvent$inboundSchema)),
    next_cursor: types.nullable(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "next_cursor": "nextCursor",
    });
  }),
);

export function queryResponseFromJSON(
  jsonString: string,
): SafeParseResult<QueryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryResponse' from JSON`,
  );
}
