/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const RateLimitedErrorStatus = {
  FourHundredAndTwentyNine: 429,
} as const;
export type RateLimitedErrorStatus = ClosedEnum<typeof RateLimitedErrorStatus>;

export const RateLimitedErrorCode = {
  RateLimited: "rate_limited",
} as const;
export type RateLimitedErrorCode = ClosedEnum<typeof RateLimitedErrorCode>;

/** @internal */
export const RateLimitedErrorStatus$inboundSchema: z.ZodMiniEnum<
  typeof RateLimitedErrorStatus
> = z.enum(RateLimitedErrorStatus);

/** @internal */
export const RateLimitedErrorCode$inboundSchema: z.ZodMiniEnum<
  typeof RateLimitedErrorCode
> = z.enum(RateLimitedErrorCode);
