/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { ClosedEnum, OpenEnum } from "../types/enums.js";

export const ScopeMismatchErrorStatus = {
  FourHundredAndThree: 403,
} as const;
export type ScopeMismatchErrorStatus = ClosedEnum<
  typeof ScopeMismatchErrorStatus
>;

export const ScopeMismatchErrorCode = {
  ScopeMismatch: "scope_mismatch",
} as const;
export type ScopeMismatchErrorCode = ClosedEnum<typeof ScopeMismatchErrorCode>;

export const RequiredScope = {
  IngestWrite: "ingest:write",
  QueryRead: "query:read",
} as const;
export type RequiredScope = OpenEnum<typeof RequiredScope>;

export const ActualScope = {
  IngestWrite: "ingest:write",
  QueryRead: "query:read",
} as const;
export type ActualScope = OpenEnum<typeof ActualScope>;

/** @internal */
export const ScopeMismatchErrorStatus$inboundSchema: z.ZodMiniEnum<
  typeof ScopeMismatchErrorStatus
> = z.enum(ScopeMismatchErrorStatus);

/** @internal */
export const ScopeMismatchErrorCode$inboundSchema: z.ZodMiniEnum<
  typeof ScopeMismatchErrorCode
> = z.enum(ScopeMismatchErrorCode);

/** @internal */
export const RequiredScope$inboundSchema: z.ZodMiniType<
  RequiredScope,
  unknown
> = openEnums.inboundSchema(RequiredScope);

/** @internal */
export const ActualScope$inboundSchema: z.ZodMiniType<ActualScope, unknown> =
  openEnums.inboundSchema(ActualScope);
