/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const ServiceUnavailableErrorStatus = {
  FiveHundredAndThree: 503,
} as const;
export type ServiceUnavailableErrorStatus = ClosedEnum<
  typeof ServiceUnavailableErrorStatus
>;

export const ServiceUnavailableErrorCode = {
  ServiceUnavailable: "service_unavailable",
} as const;
export type ServiceUnavailableErrorCode = ClosedEnum<
  typeof ServiceUnavailableErrorCode
>;

/** @internal */
export const ServiceUnavailableErrorStatus$inboundSchema: z.ZodMiniEnum<
  typeof ServiceUnavailableErrorStatus
> = z.enum(ServiceUnavailableErrorStatus);

/** @internal */
export const ServiceUnavailableErrorCode$inboundSchema: z.ZodMiniEnum<
  typeof ServiceUnavailableErrorCode
> = z.enum(ServiceUnavailableErrorCode);
