/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { ClosedEnum, OpenEnum } from "../types/enums.js";

export const UnauthenticatedErrorStatus = {
  FourHundredAndOne: 401,
} as const;
export type UnauthenticatedErrorStatus = ClosedEnum<
  typeof UnauthenticatedErrorStatus
>;

export const UnauthenticatedErrorCode = {
  Unauthenticated: "unauthenticated",
  ApiKeyRevoked: "api_key_revoked",
  ProjectDeleted: "project_deleted",
} as const;
export type UnauthenticatedErrorCode = OpenEnum<
  typeof UnauthenticatedErrorCode
>;

/** @internal */
export const UnauthenticatedErrorStatus$inboundSchema: z.ZodMiniEnum<
  typeof UnauthenticatedErrorStatus
> = z.enum(UnauthenticatedErrorStatus);

/** @internal */
export const UnauthenticatedErrorCode$inboundSchema: z.ZodMiniType<
  UnauthenticatedErrorCode,
  unknown
> = openEnums.inboundSchema(UnauthenticatedErrorCode);
