/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const UnsupportedMediaTypeErrorStatus = {
  FourHundredAndFifteen: 415,
} as const;
export type UnsupportedMediaTypeErrorStatus = ClosedEnum<
  typeof UnsupportedMediaTypeErrorStatus
>;

export const UnsupportedMediaTypeErrorCode = {
  UnsupportedMediaType: "unsupported_media_type",
} as const;
export type UnsupportedMediaTypeErrorCode = ClosedEnum<
  typeof UnsupportedMediaTypeErrorCode
>;

/** @internal */
export const UnsupportedMediaTypeErrorStatus$inboundSchema: z.ZodMiniEnum<
  typeof UnsupportedMediaTypeErrorStatus
> = z.enum(UnsupportedMediaTypeErrorStatus);

/** @internal */
export const UnsupportedMediaTypeErrorCode$inboundSchema: z.ZodMiniEnum<
  typeof UnsupportedMediaTypeErrorCode
> = z.enum(UnsupportedMediaTypeErrorCode);
