/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { ClosedEnum, OpenEnum } from "../types/enums.js";

export const ValidationErrorStatus = {
  FourHundred: 400,
} as const;
export type ValidationErrorStatus = ClosedEnum<typeof ValidationErrorStatus>;

export const ValidationErrorCode = {
  ValidationError: "validation_error",
  InvalidActorId: "invalid_actor_id",
  ReservedOrganizationId: "reserved_organization_id",
  FieldTooLong: "field_too_long",
} as const;
export type ValidationErrorCode = OpenEnum<typeof ValidationErrorCode>;

/** @internal */
export const ValidationErrorStatus$inboundSchema: z.ZodMiniEnum<
  typeof ValidationErrorStatus
> = z.enum(ValidationErrorStatus);

/** @internal */
export const ValidationErrorCode$inboundSchema: z.ZodMiniType<
  ValidationErrorCode,
  unknown
> = openEnums.inboundSchema(ValidationErrorCode);
